/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 17-feb.-2020 8:10:48 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS biometria CASCADE
;

DROP TABLE IF EXISTS cliente CASCADE
;

DROP TABLE IF EXISTS pais CASCADE
;

DROP TABLE IF EXISTS tipo_cliente CASCADE
;

DROP TABLE IF EXISTS tipo_documento CASCADE
;

/* Create Tables */

CREATE TABLE biometria
(
	id_biometria numeric(20) NOT NULL,
	bio_01 bytea NULL,
	id_cliente varchar(50) NULL
)
;

CREATE TABLE cliente
(
	id_cliente varchar(50) NOT NULL,
	id_pais varchar(3) NULL,
	id_tipo_documento varchar(2) NULL,
	nombres varchar(50) NULL,
	apellidos varchar(50) NULL,
	razon_social varchar(50) NULL,
	id_tipo_cliente varchar(3) NULL
)
;

CREATE TABLE pais
(
	id_pais varchar(3) NOT NULL,
	nombre varchar(30) NOT NULL,
	gentilicio_nacional varchar(30) NULL
)
;

CREATE TABLE tipo_cliente
(
	id_tipo_cliente varchar(3) NOT NULL,
	nombre varchar(20) NOT NULL
)
;

CREATE TABLE tipo_documento
(
	id_tipo_documento varchar(2) NOT NULL,
	nombre_documento varchar(20) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE biometria ADD CONSTRAINT "PK_biometria"
	PRIMARY KEY (id_biometria)
;

CREATE INDEX "IXFK_biometria_cliente" ON biometria (id_cliente ASC)
;

ALTER TABLE cliente ADD CONSTRAINT "PK_cliente"
	PRIMARY KEY (id_cliente)
;

CREATE INDEX "IXFK_cliente_pais" ON cliente (id_pais ASC)
;

CREATE INDEX "IXFK_cliente_tipo_cliente" ON cliente (id_tipo_cliente ASC)
;

CREATE INDEX "IXFK_cliente_tipo_documento" ON cliente (id_tipo_documento ASC)
;

ALTER TABLE pais ADD CONSTRAINT "PK_pais"
	PRIMARY KEY (id_pais)
;

ALTER TABLE tipo_cliente ADD CONSTRAINT "PK_tipo_cliente"
	PRIMARY KEY (id_tipo_cliente)
;

ALTER TABLE tipo_documento ADD CONSTRAINT "PK_tipo_documento"
	PRIMARY KEY (id_tipo_documento)
;

/* Create Foreign Key Constraints */

ALTER TABLE biometria ADD CONSTRAINT "FK_biometria_cliente"
	FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT "FK_cliente_pais"
	FOREIGN KEY (id_pais) REFERENCES pais (id_pais) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT "FK_cliente_tipo_cliente"
	FOREIGN KEY (id_tipo_cliente) REFERENCES tipo_cliente (id_tipo_cliente) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT "FK_cliente_tipo_documento"
	FOREIGN KEY (id_tipo_documento) REFERENCES tipo_documento (id_tipo_documento) ON DELETE Restrict ON UPDATE Restrict
;
