/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 17-feb.-2020 7:56:24 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS tipo_documento CASCADE
;

/* Create Tables */

CREATE TABLE tipo_documento
(
	id_tipo_documento varchar(2) NOT NULL,
	nombre_documento varchar(20) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE tipo_documento ADD CONSTRAINT "PK_tipo_documento"
	PRIMARY KEY (id_tipo_documento)
;
